import Head from 'next/head';
import Header from '@/components/Header';
import HeroSection from '@/components/HeroSection';
import Stats from '@/components/Stats';
import FeatureSection from '@/components/FeatureSection';
import ChoosePlanSection from '@/components/ChoosePlanSection';
import GlobalSection from '@/components/GlobalSection';
import ReviewSection from '@/components/ReviewSection';
import Footer from '@/components/Footer';
import NewsletterSection from '@/components/NewsletterSection';

export default function Home() {
  return (
    <>
      <Head>
        <title>Landing page</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <HeroSection />
        <Stats />
        <FeatureSection />
        <ChoosePlanSection />
        <GlobalSection />
        <ReviewSection />
        <NewsletterSection />
      </main>
      <footer>
        <Footer />
      </footer>
    </>
  );
}
