import Card, { IProduct } from "@/components/Card";
import Header from "@/components/Header";
import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
export default function Home() {
  const [featured, setFeatured] = useState<IProduct[]>([]);
  const [all, setAll] = useState<IProduct[]>([]);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await axios.get("https://dummyjson.com/products");

        setAll(res.data.products);

        setFeatured([res.data.products[0], res.data.products[1]]);
      } catch (err) {
        console.log(err);
      }
    };
    fetchData();
  }, []);

  let featuredCards: any;

  if (featured.length > 0) {
    featuredCards = featured.map((item) => {
      return <Card key={item.id} {...item} />;
    });
  }

  let allCards;
  if (all.length > 0) {
    allCards = all.map((item) => {
      return <Card key={item.id} {...item} />;
    });
  }

  return (
    <>
      <Head>
        <title>Store page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-4 sm:px-10 md:px-28 md: py-10 bg-primaryBg min-h-screen">
        <Header />

        <div className="w-full my-4">
          <input
            className="py-2 text-xs px-3 rounded-md border focus:border-[#E8E8E9] border-[#E8E8E8] w-full  sm:w-72"
            type={"text"}
            placeholder="🔍  Search"
          />
        </div>

        <section>
          <h3 className=" font-semibold text-md my-5 mt-8 ">Featured Events</h3>
          <div className="flex space-x-3 overflow-x-scroll snap-x w-full scroll-mb-4">
            {featuredCards}
          </div>
        </section>
        <section>
          <h3 className=" font-semibold text-md my-5 mt-8 ">All Events</h3>
          <div className="flex flex-wrap justify-evenly">{allCards}</div>
        </section>
      </main>
    </>
  );
}
